// <auto-generated />
namespace GraduationProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addconirmedanddlivereddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addconirmedanddlivereddate));
        
        string IMigrationMetadata.Id
        {
            get { return "202105131728016_add-conirmed-and-dlivered-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
